import { useEffect, useState } from 'react';
import { supabase } from '../../supabase';
import { ztLog } from '../../lib/telemetry';
import { Icon, GameBadge } from '../../components/ZeroTwoUI';
import { PlayerHistoryView } from '../history/PlayerHistoryView';
import { PlayerCentralView } from './PlayerCentralView';
import { PlayerGamesView } from './PlayerGamesView';
import { PlayerAccountView } from './PlayerAccountView';
import { DebugConsole } from '../debug/DebugConsole';
import { ValorantFeatureGate } from '../valorant/ValorantFeatureGate';

export function PlayerHome({session,nickname,onSetup,onLogout}:{session:any,nickname:string,onSetup:()=>void,onLogout:()=>void}){
 const [riot,setRiot]=useState<any>(null),[profile,setProfile]=useState<any>(null),[dna,setDna]=useState<any>(null),[dnaPersisted,setDnaPersisted]=useState(false),[publicProfile,setPublicProfile]=useState<any>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[analyzing,setAnalyzing]=useState(false),[notice,setNotice]=useState(''),[view,setView]=useState<'central'|'history'|'games'|'account'>('central'),[history,setHistory]=useState<any>(null),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState(''),[firstRun,setFirstRun]=useState(false),[debugOpen,setDebugOpen]=useState(false),[debugLogs,setDebugLogs]=useState<any[]>([]),[debugLoading,setDebugLoading]=useState(false),[activeGame,setActiveGameState]=useState<'lol'|'valorant'>(()=>sessionStorage.getItem('zt_player_focus')==='valorant'||sessionStorage.getItem('zt_active_game')==='valorant'?'valorant':'lol');
 const gamerName=profile?.nickname||nickname||'PLAYER';
 function setActiveGame(game:'lol'|'valorant'){setActiveGameState(game);sessionStorage.setItem('zt_active_game',game);ztLog(session.user.id,'player.game_context.changed',{area:'player',context:{game}})}
 async function loadPlayer(){const started=performance.now();setLoading(true);ztLog(session.user.id,'player.load.start',{area:'player'});const [pq,rq,dq]=await Promise.all([supabase.from('profiles').select('*').eq('user_id',session.user.id).maybeSingle(),supabase.from('riot_accounts').select('*').eq('user_id',session.user.id).maybeSingle(),supabase.from('player_dna_snapshots').select('*').eq('user_id',session.user.id).maybeSingle()]);const p=pq.data,r=rq.data,d=dq.data;for(const [source,q] of [['profile',pq],['riot',rq],['dna',dq]] as const)if(q.error)ztLog(session.user.id,'player.load.error',{level:'error',area:'player',message:q.error.message,context:{source,code:q.error.code}});setProfile(p);setRiot(r);setDna(d);setDnaPersisted(!!d);let fallback:any=null;if(r){const {data:pub,error:pubError}=await supabase.functions.invoke('public-lol-profile',{body:{gameName:r.game_name,tagLine:r.tag_line,region:r.region||'americas',platform:r.platform||'br1'}});if(!pubError&&!pub?.error){setPublicProfile(pub);if(!d&&pub?.summary){fallback={user_id:session.user.id,matches_analyzed:pub.summary.matches||0,primary_position:pub.summary.primaryPosition||null,top_champions:pub.summary.topChampions||[],metrics:{wins:pub.summary.wins,losses:pub.summary.losses,winRate:pub.summary.winRate,avgKda:pub.summary.avgKda,avgCsPerMin:pub.summary.avgCsPerMin,avgVisionPerMin:pub.summary.avgVisionPerMin,avgDamagePerMin:pub.summary.avgDamagePerMin,mainContext:pub.summary.mainContext,modeSummaries:pub.modeSummaries||[]},dimensions:{},confidence:pub.summary.confidence==='BOA'?'good':pub.summary.confidence==='EM FORMAÇÃO'?'developing':'initial',evidence:(pub.analysis?.signals||[]).map((x:string,i:number)=>({key:'public-'+i,text:x})),_fallback:true};setDna(fallback)}}}setLoading(false);ztLog(session.user.id,'player.load.complete',{area:'player',duration_ms:Math.round(performance.now()-started),context:{hasProfile:!!p,hasGame:!!r,hasDna:!!d,hasPublicFallback:!!fallback,dnaMatches:d?.matches_analyzed??fallback?.matches_analyzed??0}})}
 useEffect(()=>{const onError=(e:ErrorEvent)=>ztLog(session.user.id,'browser.error',{level:'error',area:'runtime',message:e.message,context:{file:e.filename?.split('/').pop(),line:e.lineno,col:e.colno}});const onReject=(e:PromiseRejectionEvent)=>ztLog(session.user.id,'browser.unhandled_rejection',{level:'error',area:'runtime',message:e.reason instanceof Error?e.reason.message:String(e.reason||'Unhandled promise rejection').slice(0,250)});window.addEventListener('error',onError);window.addEventListener('unhandledrejection',onReject);ztLog(session.user.id,'app.session.ready',{area:'app',context:{viewport:`${window.innerWidth}x${window.innerHeight}`}});return()=>{window.removeEventListener('error',onError);window.removeEventListener('unhandledrejection',onReject)}},[session.user.id]);
 useEffect(()=>{loadPlayer()},[session.user.id]);useEffect(()=>{if(sessionStorage.getItem('zt_pending_action')==='find02')sessionStorage.removeItem('zt_pending_action')},[]);useEffect(()=>{if(!loading&&riot&&!firstRun){setFirstRun(true);if(!dnaPersisted&&!analyzing)analyzeDna(true)}},[loading,riot?.user_id,dnaPersisted]);
 async function refreshRiot(){if(!riot)return;const started=performance.now();setRefreshing(true);ztLog(session.user.id,'game.refresh.start',{area:'riot',context:{game:'lol',server:riot.platform||'br1'}});setNotice('Atualizando dados Riot...');const {data,error}=await supabase.functions.invoke('riot-lol-player',{body:{gameName:riot.game_name,tagLine:riot.tag_line,region:riot.region||'americas',platform:riot.platform||'br1',includeSummoner:true,forceRefresh:true}});if(error||data?.error){setNotice(data?.message||'Não foi possível atualizar agora.');ztLog(session.user.id,'game.refresh.error',{level:'error',area:'riot',duration_ms:Math.round(performance.now()-started),message:data?.message||error?.message||'Riot refresh failed'});setRefreshing(false);return}const level=data.lol?.summoner?.summonerLevel??riot.summoner_level;await supabase.from('riot_accounts').update({summoner_level:level,updated_at:new Date().toISOString()}).eq('user_id',session.user.id);setRiot((x:any)=>({...x,summoner_level:level,updated_at:new Date().toISOString()}));setNotice('Dados Riot atualizados agora.');setRefreshing(false);ztLog(session.user.id,'game.refresh.complete',{area:'riot',duration_ms:Math.round(performance.now()-started),context:{game:'lol',level}})}
 async function analyzeDna(silent=false){const lockKey=`zt_dna_mm2_lock_${session.user.id}`,failKey=`zt_dna_mm2_fail_${session.user.id}`;const now=Date.now(),locked=Number(sessionStorage.getItem(lockKey)||0),failed=Number(sessionStorage.getItem(failKey)||0);if(now-locked<45000){ztLog(session.user.id,'dna.analyze.skipped',{area:'dna',context:{reason:'in_flight'}});return}if(silent&&now-failed<300000){ztLog(session.user.id,'dna.analyze.skipped',{area:'dna',context:{reason:'failure_cooldown'}});return}sessionStorage.setItem(lockKey,String(now));const started=performance.now();setAnalyzing(true);ztLog(session.user.id,'dna.analyze.start',{area:'dna',context:{silent}});if(!silent)setNotice('Analisando suas partidas recentes...');const {data,error}=await supabase.functions.invoke('lol-gaming-dna',{body:{}});if(error||data?.error){if(!silent)setNotice(data?.message||'Ainda não conseguimos atualizar seu Gaming DNA.');ztLog(session.user.id,'dna.analyze.error',{level:'error',area:'dna',duration_ms:Math.round(performance.now()-started),message:data?.message||error?.message||'DNA function failed'});sessionStorage.setItem(failKey,String(Date.now()));sessionStorage.removeItem(lockKey);setAnalyzing(false);return}setDna(data.dna);setDnaPersisted(true);ztLog(session.user.id,'dna.analyze.complete',{area:'dna',duration_ms:Math.round(performance.now()-started),context:{matches:data.dna?.matches_analyzed??0,confidence:data.dna?.confidence,position:data.dna?.primary_position}});if(!silent){const n=data.dna.matches_analyzed;setNotice(`Gaming DNA atualizado com ${n} ${n===1?'partida':'partidas'}.`)}sessionStorage.removeItem(failKey);sessionStorage.removeItem(lockKey);setAnalyzing(false)}
 async function openHistory(deepen=false){setView('history');if(history&&!deepen)return;const started=performance.now();setHistoryLoading(true);setHistoryError('');ztLog(session.user.id,'history.open.start',{area:'history',context:{deepen}});const {data,error}=await supabase.functions.invoke('player-history',{body:{depth:50,batch:deepen?12:8,timezoneOffset:new Date().getTimezoneOffset()}});if(error||data?.error){const msg=data?.message||error?.message||'Não foi possível carregar sua história agora.';setHistoryError(msg);ztLog(session.user.id,'history.open.error',{level:'error',area:'history',message:msg,duration_ms:Math.round(performance.now()-started)});setHistoryLoading(false);return}setHistory(data);setHistoryLoading(false);ztLog(session.user.id,'history.open.complete',{area:'history',duration_ms:Math.round(performance.now()-started),context:{games:data?.summary?.games||0,loaded:data?.coverage?.loaded||0,remaining:data?.coverage?.remaining||0}})}
 async function openDebug(){setDebugOpen(true);setDebugLoading(true);const {data,error}=await supabase.from('client_event_logs').select('id,event_name,level,area,message,context,duration_ms,created_at,session_id').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(80);setDebugLogs(error?[]:(data||[]));setDebugLoading(false)}
 const debugAllowed=new URLSearchParams(location.search).get('debug')==='1';const mainPublicMode=publicProfile?.modeSummaries?.find((m:any)=>m.name===publicProfile?.summary?.mainContext)||null,soloRank=publicProfile?.ranked?.find((r:any)=>r.queue==='SOLO/DUO')||publicProfile?.ranked?.[0]||null;const riotId=riot?`${riot.game_name}#${riot.tag_line}`:'Riot ID não informado', server=(riot?.platform||'br1').toUpperCase(), updated=riot?.updated_at?new Date(riot.updated_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
 return <section className="playerClient riotLifeClient">
  <aside className="clientSide riotLifeSide">
    <a className="brand" href="#"><b className="brandMark"><img src="/zerotwo.gg/assets/zerotwo/zerotwo-mark.svg" alt=""/></b> ZERO<span>TWO</span><small>.GG</small></a>
    <div className="clientIdentity">
      <span className="clientAvatar">01<i/></span>
      <div><small>RIOT LIFE ATIVA</small><b>{gamerName}</b><em>{riot?riotId:'IDENTIDADE EM FORMAÇÃO'}</em>{activeGame==='valorant'?<GameBadge game="valorant" label="VALORANT"/>:riot&&<GameBadge game="lol" label="LEAGUE OF LEGENDS"/>}</div>
    </div>
    <nav className="clientNav">
      <button className={view==='central'?'active':''} onClick={()=>setView('central')}><i><Icon name="spark"/></i><span>Minha Riot Life</span></button>
      <button className={view==='history'?'active':''} onClick={()=>openHistory(false)}><i><Icon name="dna"/></i><span>História</span></button>
      <button className={view==='games'?'active':''} onClick={()=>setView('games')}><i><Icon name="game"/></i><span>Jogos</span></button>
      <button className={view==='account'?'active':''} onClick={()=>setView('account')}><i><Icon name="user"/></i><span>Conta</span></button>
    </nav>
    <div className="clientStatus"><span><i/> RIOT LIFE ONLINE</span><small>ZEROTWO // CONECTADO</small>{debugAllowed&&<button className="debugTrigger" onClick={openDebug}>DIAGNÓSTICO</button>}</div>
    <button className="clientLogout" onClick={onLogout}><Icon name="login"/> SAIR</button>
  </aside>

  <main className="clientMain riotLifeMain">
    <header className="clientTop riotLifeTop">
      <div><small>ZEROTWO // MINHA RIOT LIFE</small><h1>OLÁ, <span>{gamerName}.</span></h1></div>
      <div className="clientTopActions"><button onClick={()=>setView('games')}><GameBadge game={activeGame}/>{activeGame==='valorant'?' VALORANT':' LEAGUE'}</button><span>01</span></div>
    </header>

    {loading?<div className="clientLoading">CARREGANDO SUA RIOT LIFE<span>...</span></div>
    :view==='history'?(activeGame==='valorant'?<ValorantFeatureGate feature="history" onUseLeague={()=>setActiveGame('lol')}/>:<PlayerHistoryView data={history} loading={historyLoading} error={historyError} onDeepen={()=>openHistory(true)}/>)
    :view==='games'?<PlayerGamesView riot={riot} riotId={riotId} server={server} onSetup={onSetup} activeGame={activeGame} setActiveGame={setActiveGame}/>
    :view==='account'?<PlayerAccountView gamerName={gamerName} riotId={riotId} server={server} riot={riot} onSetup={onSetup} onLogout={onLogout}/>
    :<PlayerCentralView activeGame={activeGame} setActiveGame={setActiveGame} riot={riot} riotId={riotId} server={server} onSetup={onSetup} notice={notice} publicProfile={publicProfile} analyzeDna={analyzeDna} analyzing={analyzing} mainPublicMode={mainPublicMode} soloRank={soloRank} history={history} openHistory={openHistory} dna={dna}/>}

    <DebugConsole debugOpen={debugOpen} setDebugOpen={setDebugOpen} debugLogs={debugLogs} openDebug={openDebug} debugLoading={debugLoading}/>
    <footer className="clientFooter"><span>ZEROTWO.GG // RIOT LIFE</span><b>SUA HISTÓRIA RIOT, VIVA.</b><small><Icon name="status"/> ONLINE</small></footer>
  </main>
 </section>
}
